name: get_web_renderer
description: An easy way to get the current renderer (HTML or CanvasKit in Web platform and Other for other platforms).
version: 1.2.1
homepage: https://github.com/lamnhan066/get_web_renderer

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
