name: get_web_renderer
description: An easy way to get the current renderer (HTML or CanvasKit in Web platform and Other for other platforms).
version: 1.1.0
homepage: https://github.com/vursin/get_web_renderer

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.19.3